# Generated by Django 4.2.1 on 2023-06-05 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('artists', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('duration', models.CharField(default='00:00', max_length=5)),
                ('isrc', models.CharField(max_length=12, unique=True)),
                ('artist', models.ManyToManyField(related_name='tracks', to='artists.artist')),
            ],
        ),
    ]
