# Generated by Django 4.2.1 on 2023-06-03 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0001_initial'),
        ('tracks', '0002_alter_track_duration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='track',
            name='artist',
        ),
        migrations.AddField(
            model_name='track',
            name='artist',
            field=models.ManyToManyField(related_name='tracks', to='artists.artist'),
        ),
    ]
